#if !canImport(ObjectiveC)
import XCTest

extension DaggerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DaggerTests = [
        ("testDagger", testDagger),
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DaggerTests.__allTests__DaggerTests),
    ]
}
#endif
